<?php

namespace PetTrafficKing\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetRepository extends EntityRepository
{
}
